austen = Author.create(name: "Jane Austen")
pratchett = Author.create(name: "Terry Pratchett")
gaiman = Author.create(name: "Neil Gaiman")
kingsolver = Author.create(name: "Barbara Kingsolver")
liu = Author.create(name: "Cixin Liu")
herbert = Author.create(name: "Frank Herbert")
harkaway = Author.create(name: "Nick Harkaway")
novik = Author.create(name: "Naomi Novik")
murakami = Author.create(name: "Haruki Murakami")
hannah = Author.create(name: "Kristin Hannah")
tartt = Author.create(name: "Donna Tartt")

pride_and_prejudice = Book.create!(title: "Pride and Prejudice", year: 1813, length: 432, authors: [austen], cover_image: "https://images-na.ssl-images-amazon.com/images/I/51sOyMmEYBL._SX310_BO1,204,203,200_.jpg")
good_omens = Book.create!(title: "Good Omens", year: 1990, length: 288, authors: [pratchett, gaiman], cover_image: "https://images-na.ssl-images-amazon.com/images/I/81Ig%2Br7RTKL.jpg")
sense_and_sensibility = Book.create!(title: "Sense and Sensibility", year: 1811, length: 352, authors: [austen], cover_image: "https://images.gr-assets.com/books/1176166955l/600331.jpg")
poisonwood_bible = Book.create!(title: "The Poisonwood Bible", year: 1998, length: 546, authors: [kingsolver], cover_image: "https://i.pinimg.com/236x/85/8f/8e/858f8e3a58b6cde30f804495a7a70b0f--barbara-kingsolver-bible.jpg")
three_body = Book.create!(title: "The Three-Body Problem", year: 2014, length: 400, authors: [liu], cover_image: "https://images.gr-assets.com/books/1415428227l/20518872.jpg")
dune = Book.create!(title: "Dune", year: 1999, length: 517, authors: [herbert], cover_image: "https://images.gr-assets.com/books/1395160437l/53747.jpg")
gone_away = Book.create!(title: "The Gone-Away World", year: 531, length: 544, authors: [harkaway], cover_image: "https://images.gr-assets.com/books/1328322676l/3007704.jpg" )
uprooted = Book.create!(title: "Uprooted", year: 2015, length: 448, authors: [novik], cover_image: "http://t3.gstatic.com/images?q=tbn:ANd9GcQlUX2MfH_OzRAjN9VOF-Ftb-7Jge7kFxHt0ou0pAOiGzimph6h")
spinning_silver = Book.create!(title: "Spinning Silver", year: 2018, length: 480, authors: [novik], cover_image: "http://t0.gstatic.com/images?q=tbn:ANd9GcRrXzs8bmTSq0LoJBO6nLkQK5A0W6Bay0LZ3kkjRK4zidHoyR73")
graveyard_book = Book.create!(title: "The Graveyard Book", year: 2008, length: 312, authors: [gaiman], cover_image: "https://upload.wikimedia.org/wikipedia/en/3/3e/TheGraveyardBook_Hardcover.jpg")
iq84= Book.create!(title: "1Q84", year: 2011, length: 1184, authors: [murakami], cover_image: "https://booklife.com/image-factory/http/localhost/amazongetcover/9780307593313.jpg/w204.jpg")
nightingale= Book.create!(title: "The Nightingale", year: 2015, length: 440, authors: [hannah], cover_image: "http://t1.gstatic.com/images?q=tbn:ANd9GcShNR3u-bHpxG48-M8415L_BR9ABzRIJt7my0BBJGHI6XivaACu")
goldfinch = Book.create!(title: "The Goldfinch", year: 2013, length: 784, authors: [tartt], cover_image: "https://www.littlebrown.com/wp-content/uploads/2017/06/9780316055437.jpg?fit=439%2C675")


april = User.create(name: "ReaderGirl")
zach = User.create(name: "Zach N.")

sense_and_sensibility.reviews.create!(title: "Austen is the best", rating: 4, user: april, description: "It's not quite P&P, but it's probably my second-favorite Jane Austen book.")
sense_and_sensibility.reviews.create!(title: "Girl books are so boring", rating: 1, user: zach, description: "Really long and dull.")
dune.reviews.create!(title: "Classic and awesome", rating: 5, user: april, description: "Has so many now-familiar sci-fi tropes. Such a great book!")
pride_and_prejudice.reviews.create!(title: "A perfect book", rating: 5, user: april, description: "Beautiful. Charming. Wonderful.")
poisonwood_bible.reviews.create!(title: "Incredible", rating: 5, user: april, description: "Definitely one of my top 5 of all time. So moving.")
poisonwood_bible.reviews.create!(title: "Didn't really like it", rating: 2, user: zach, description: "I thought there would be more bible stories")
uprooted.reviews.create!(title: "One of my all-time faves", rating: 5, user: april, description: "One of the few books I finished and then immediately re-read again. Love this book.")
spinning_silver.reviews.create(title: "Amazing follow-up to Uprooted", rating: 5, user: april, description: "I was nervous this one wouldn't be as good as Uprooted, but it is!")
graveyard_book.reviews.create(title: "Stole my heart", rating: 5, user: april, description: "If you don't love this book, you might not have feelings.")
three_body.reviews.create(title: "Insane!", rating: 5, user: april, description: "These books are SO impressive, with such incredible, thought-provoking scope. Highly recommend if you love sci-fi.")
three_body.reviews.create(title: "Too long; didn't read", rating: 3, user: zach, description: "I don't read very fast so this book was too hard for me.")
iq84.reviews.create(title: "Fine?", rating: 3, user: april, description: "This took me forever to finish, and I'm still not sure whether I actually enjoyed it or not. It's a weird one.")
gone_away.reviews.create(title: "Loved it!", rating: 4, user: april, description: "This book is so unique and interesting! Slow start, amazing finish.")
nightingale.reviews.create(title: "Meh", rating: 2, user: april, description: "I didn't love this book as much as everyone else did. How much WWII fiction does the world really need.")
goldfinch.reviews.create(title: "Pulitzer, huh?", rating: 1, user: april, description: "I thought it was annoying.")
